all: main ibandeja

main.o : main.cpp
	g++ -Wall main.cpp -c
main   : main.o
	g++ -Wall main.o -o main
	
ibandeja.o : ibandeja.cpp
	g++ -Wall ibandeja.cpp -c
ibandeja   : ibandeja.o
	g++ -Wall ibandeja.o -o ibandeja